### ISSUE TITLE
Wave Spawn Location

### ISSUE THREAD

**Issue by MikeMasters** [ScureX/TakyonsWaveDefend#1]
Great Mod for Wave defending in Reforger. Can you make the "Wave Spawn Location" to set the faction that is going to spawn. Now only AFRF Units are Spawning? like FIA faction.

**Comment by ScureX** [comment]
Thanks for your interest. I havent been active in Reforger and thus this mod for a while, so it may take some time till i implement anything new. 
You can always make a pull request if you implement this feature and i will merge it and republish. 
Alternatively you can make a new mod with my mod as a dependency and override this variable:
https://github.com/ScureX/TakyonsWaveDefend/blob/fdd09b8cc5dfd400aceed6d38a34516af580e8c9/scripts/Game/Components/Spawner/spawner.c#L159-L165

i _think_ this can be done by simply making a new file and putting
```
modded class TKY_SpawnerComponent
{
    override void InitializeWave()
    {
        enemyPrefabs = new array<ref Enemy>();
        enemyPrefabs = 
        {
            /* ADD YOUR ENEMIES HERE */
        };

        waypointPrefabs = new array<ref ResourceName>();
        waypointPrefabs =
        {
            "{D9C14ECEC9772CC6}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Defend.et",
            "{FFF9518F73279473}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Move.et",
            "{3C790BB71C5CD960}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_ForcedMove.et"
        };

        waypointWeights = new array<float>();
        waypointWeights = { 0.4, 0.4, 0.2 };
    }
};
```
but as i said i havent dabbled in this for quite some time, so if this doesnt work refer to the docs here: https://community.bistudio.com/wiki/Arma_Reforger:Scripting:_Keywords#vanilla

**Comment by MikeMasters** [comment]
> Thanks for your interest. I havent been active in Reforger and thus this mod for a while, so it may take some time till i implement anything new. You can always make a pull request if you implement this feature and i will merge it and republish. Alternatively you can make a new mod with my mod as a dependency and override this variable:
> 
> https://github.com/ScureX/TakyonsWaveDefend/blob/fdd09b8cc5dfd400aceed6d38a34516af580e8c9/scripts/Game/Components/Spawner/spawner.c#L159-L165
> 
> i _think_ this can be done by simply making a new file and putting
> 
> ```
> modded class TKY_SpawnerComponent
> {
>     override void InitializeWave()
>     {
>         enemyPrefabs = new array<ref Enemy>();
>         enemyPrefabs = 
>         {
>             /* ADD YOUR ENEMIES HERE */
>         };
> 
>         waypointPrefabs = new array<ref ResourceName>();
>         waypointPrefabs =
>         {
>             "{D9C14ECEC9772CC6}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Defend.et",
>             "{FFF9518F73279473}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Move.et",
>             "{3C790BB71C5CD960}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_ForcedMove.et"
>         };
> 
>         waypointWeights = new array<float>();
>         waypointWeights = { 0.4, 0.4, 0.2 };
>     }
> };
> ```
> 
> but as i said i havent dabbled in this for quite some time, so if this doesnt work refer to the docs here: https://community.bistudio.com/wiki/Arma_Reforger:Scripting:_Keywords#vanilla

**Comment by MikeMasters** [comment]
Thank you for your explanation. I am not that good in scripting that i can suggest a pull request. While im struggeling to get our community from A3 to Reforger ,mission making is getting a bit more complicated. Therefore im leaning more on mods then before. Mods like this make mission making in GM easier and playable. 

I saw the file Spawner.c with the 4 types of units in it. Instead of editing that object, would it be easier to make a spawner per faction? So 1 for bluefor 1 for opfor 1 for fia. That way you have the choice, without tinkering with the object itself (copy/paste). Or is that the same as you suggested? "i think this can be done by simply making a new file and putting"

I will try to make my own MOD with your mod as dependency and copy/paste the spawner for bluefor and fia.

Hopefully you will find the time and maybe implement this. That would be so cool ;-)

**Comment by ScureX** [comment]
Had some time on my hands and decided to make a (very) quick implementation of this. You now have  the option between RFAF, USAF and INDFOR if you double click the tent. The logic remains in `spawner.c` where you could just add more factions or change what gets spawned. 
If you add additional factions make sure to add them in the enum:
https://github.com/ScureX/TakyonsWaveDefend/blob/7c012cc7d7859b2fea8fb47a209cbad8f2447c41/scripts/Game/Components/Spawner/spawner.c#L35-L39

and add them in the Edit.conf:
![image](https://github.com/user-attachments/assets/15c02d7e-f465-4481-b43f-07fb63517b99)

**MAKE SURE THE NUMBER YOU ASSIGN IN THE ENUM MATCHES THE `Entry Float Value` IN THE CONFIG**

**Comment by MikeMasters** [comment]
![image](https://github.com/user-attachments/assets/6160ffc3-3707-42f1-b448-9cbe872dc054)
Very cool, thank you for that! Unfortunately the spawns don't work anymore. I have tested it without any other mods then depended on Arland GM.

**Comment by ScureX** [comment]
It... worked for me? Did you activate the tent?

**Comment by MikeMasters** [comment]
![image](https://github.com/user-attachments/assets/79d42888-4d89-4788-a210-e02df587e008)
On the dedicated server it works! on local host it doesn't. So its good for now i think ;-)
